### ISSUE TITLE
low image quality in /docs/guidelines/ in Dark Mode

### ISSUE THREAD

**Issue by Pushkarm029** [fossology/gsoc#196]
### Description

Please describe your issue in few words here.
- Image quality significantly decreases user experience in dark mode.

#### How to reproduce
- simply go to this page : [https://fossology.github.io/gsoc/docs/guidelines/](https://fossology.github.io/gsoc/docs/guidelines/)

#### Screenshots

![image](https://github.com/fossology/gsoc/assets/81290616/70c77391-3b8f-448b-9813-28ece4f2ac25)

Expected : 
![image](https://github.com/fossology/gsoc/assets/81290616/8661f940-43bb-470e-8ff7-9a23063d6f5d)

### Versions

* Last commit id on master: 1ad1e12
* Operating System (lsb_release -a): windows 11
* Browser [e.g. chrome, safari]: microsoft edge

### Logs

Any logs (if any) generated in

**Comment by anproghub** [comment]
that's the PNG with a transparent background, there is no issue with the code only the image quality is degraded.
