### ISSUE TITLE
Style enhancement needed

### ISSUE THREAD

**Issue by sahiljena** [fossology/gsoc#32]
### Description
I have noticed a few places where the websites needs a few style changes.
<table>
  <tr>
    <td valign="top"><img src="https://i.ibb.co/vchfWZs/foss-gsoc-ui-1.png" width="200"/></td>
    <td valign="top"><img src="https://i.ibb.co/wp9q497/foss-gsoc-ui-2.png" width="200"/></td>
    <td valign="top"><img src="https://i.ibb.co/gRCTjj9/foss-gsoc-ui-3.png" width="200"/></td>
  </tr>
<tr>
   <td>
       <li>On small screens this section looks a bit stretched</li>
       <li>Adding some padding to it can fix this</li>
    </td>
     <td>
       <li>Caption on image crousel looks weird</li>
    </td>
    <td>
       <li>Footer link rows seems to be  in the left</li>
       <li>Centering them can make it look better</li>
    </td>
  </tr>
 </table>

Should I work on it to fix?

**Comment by GMishx** [comment]
Please feel free to work on it.
